

apiVersion: apps/v1
kind: Deployment
metadata:
  name: nws-oax-bot
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nws-oax-bot
  template:
    metadata:
      labels:
        app: nws-oax-bot
    spec:
      containers:
      - name: nws-oax-bot
        image: maxwelldps/xmpp-matrix-relayv2:latest
        command: ["xmpp-bot", "/data/config.yaml"]
        imagePullPolicy: Always
        env:
          - name: CONFIG_PATH
            value: /data/config.yml
        volumeMounts:
        - name: config-volume
          mountPath: /data
        - name: data-volume
          mountPath: /matrix
      volumes:
      - name: config-volume
        configMap:
          name: oax-config
      - name: data-volume
        persistentVolumeClaim:
          claimName: oax-matrix
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: oax-config
data:
  config.yaml: |-
    # Welcome to the sample config file
    # Below you will find various config sections and options
    # Default values are shown

    # The string to prefix messages with to talk to the bot in group chats
    command_prefix: "!"

    # Options for connecting to the bot's Matrix account
    matrix:
      # The Matrix User ID of the bot account
      user_id: "@nws-bot:matrix.panik.io"
      # Matrix account password (optional if access token used)
      user_password: "-yfvoyidfcjykdcioyklfcsoywiefgdoyifvciyKDFOUYDIYTdsits8596td9s8iutcfudtxt5d-"
      # Matrix account access token (optional if password used)
      #user_token: ""
      # The URL of the homeserver to connect to
      homeserver_url: https://matrix.panik.io
      # The device ID that is **non pre-existing** device
      # If this device ID already exists, messages will be dropped silently in encrypted rooms
      device_id: NWSOAXYEJO
      generate_device_id: true
      # What to name the logged in device
      device_name: i-nwsoax

    xmpp:
      username: ham-max.watermolen@nwschat.weather.gov
      password: '7Hf3tAS5@YwA6.Z'
      room: oaxchat@conference.nwschat.weather.gov
      nick: ham-max.watermolen

      matrix_relay_room: "!tEJvkXtPtMauYhkaUr:matrix.panik.io"

      mute_users: []
      #  - 'nwsbot'

      keyword_alerts:
        enabled: true
        alert_prefix: '@room '
        keywords:
            - tornado
            - emergency

    bot:
      name: "WX Bot v9"
      rules: "Dont share any info weather bot posts to the internet, or any party that my misunderstand the data. NO COMMERICAL USE ⚠️ ... Weather bot will fuck you up 🤖"
      admins: []
    storage:
      # The database connection string
      # For SQLite3, this would look like:
      #     database: "sqlite://bot.db"
      # For Postgres, this would look like:
      #     database: "postgres://username:password@localhost/dbname?sslmode=disable"
      database: "sqlite://bot.db"
      # The path to a directory for internal bot storage
      # containing encryption keys, sync tokens, etc.
      store_path: "/matrix"

    # Logging setup
    logging:
      # Logging level
      # Allowed levels are 'INFO', 'WARNING', 'ERROR', 'DEBUG' where DEBUG is most verbose
      level: INFO
      # Configure logging to a file
      file_logging:
        # Whether logging to a file is enabled
        enabled: false
        # The path to the file to log to. May be relative or absolute
        filepath: /matrix/bot.log
      # Configure logging to the console output
      console_logging:
        # Whether logging to the console is enabled
        enabled: true


---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: oax-matrix
spec:
  storageClassName: longhorn
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
